const frasesMotivadoras = [
    "Eres el reflejo de tu paz interior.",
    "La energía que emites es la que atraes.",
    "Cada paso que das es un paso hacia tu transformación.",
    "La serenidad comienza cuando decides soltar lo que no puedes controlar.",
    "Confía en tu intuición; es la voz de tu alma.",
    "El amor propio es el primer paso hacia la sanación.",
    "No hay límites para lo que puedes lograr cuando te conectas con tu esencia.",
    "Tu cuerpo es un templo, cuídalo con amor y respeto.",
    "La naturaleza te habla, solo tienes que escuchar.",
    "Tu bienestar es un reflejo de lo que piensas y sientes.",
    "Eres un ser divino, con un propósito único en este universo.",
    "Cada día es una oportunidad para renovar tu energía.",
    "Vivir en armonía con el universo trae paz al alma.",
    "La verdadera belleza proviene de dentro hacia afuera.",
    "El poder de sanación está dentro de ti.",
    "Tu alma tiene la capacidad de brillar sin límites.",
    "El universo siempre conspira a tu favor cuando vives en alineación con tu ser.",
    "La abundancia fluye hacia ti cuando cultivas gratitud.",
    "La paciencia y la perseverancia son las claves de tu evolución.",
    "Escucha tu corazón, es tu brújula interna.",
    "La meditación te conecta con tu sabiduría más profunda.",
    "La paz interior se encuentra en el presente, no en el futuro.",
    "Suelta lo que no te sirve y da espacio a lo nuevo.",
    "Eres una mujer poderosa, capaz de crear la vida que sueñas.",
    "Tu energía es tu mayor aliada, cuídala con amor.",
    "La armonía entre mente, cuerpo y espíritu es la verdadera riqueza.",
    "Cada desafío es una oportunidad para crecer y aprender.",
    "La conexión con tu ser interior es tu mayor fuente de fortaleza.",
    "Cada respiro te acerca más a tu equilibrio interno.",
    "El amor incondicional comienza contigo misma.",
    "Confía en el proceso de la vida, todo sucede por una razón.",
    "Tu propósito es único, y el mundo necesita tu luz.",
    "El cambio empieza dentro de ti, cuando decides verlo.",
    "La naturaleza es tu guía, conecta con ella para sanar.",
    "La gratitud transforma tu vida y tu visión del mundo.",
    "Tu felicidad depende de cómo eliges ver la vida.",
    "La paz es un estado interno, no una circunstancia externa.",
    "Cada día es una nueva oportunidad para reconectar con tu ser.",
    "La sabiduría de tu alma siempre te llevará por el camino correcto.",
    "El amor propio es la clave para vivir una vida plena.",
    "La calma en tu mente te lleva a la claridad en tu vida.",
    "Eres un ser ilimitado, capaz de todo lo que te propongas.",
    "La verdadera riqueza está en tu salud, bienestar y paz interior.",
    "Escucha a tu cuerpo, él te habla constantemente.",
    "Tu energía es tan poderosa como tu intención.",
    "La vida te está guiando hacia tu mejor versión.",
    "La conexión con la naturaleza trae claridad y sanación.",
    "Tu alma tiene un propósito y está en constante expansión.",
    "Cada pensamiento positivo que tienes es una semilla para tu futuro.",
    "Sigue tu intuición; es la voz divina que te guía.",
    "El universo está lleno de posibilidades infinitas para ti.",
    "La resiliencia es la capacidad de florecer después de cada tormenta.",
    "La paz que buscas está dentro de ti, no fuera.",
    "Cada momento es una oportunidad para reiniciar y comenzar de nuevo.",
    "La mente clara es el primer paso hacia el bienestar.",
    "El amor que das a los demás comienza con el amor que te das a ti misma.",
    "Confía en tu poder interior, es infinito.",
    "Tu luz interior es tu mayor fortaleza.",
    "La gratitud transforma el caos en calma.",
    "La aceptación es el primer paso hacia la sanación.",
    "Lo que eres en tu interior se refleja en el mundo exterior.",
    "El bienestar es un estilo de vida, no un destino.",
    "El camino hacia la paz comienza con la aceptación de ti misma.",
    "La energía positiva fluye hacia ti cuando te abres a ella.",
    "La vida es un reflejo de tus pensamientos y emociones.",
    "Tu bienestar está en tus manos, cuídalo con amor.",
    "Cuando te alineas con tu ser, todo lo que necesitas llega a ti.",
    "Recuerda que cada desafío es solo un peldaño hacia tu crecimiento.",
    "Tú eres la creadora de tu realidad.",
    "La sabiduría está en escuchar tu voz interior.",
    "La verdadera belleza es la que emana de tu alma.",
    "Cada pensamiento positivo te acerca a tu ser divino.",
    "La vida siempre está trabajando a tu favor, confía en ella.",
    "La paz comienza en el momento en que eliges soltar el control.",
    "Eres capaz de transformar tu vida con cada decisión que tomas.",
    "La sanación comienza cuando dejas ir lo que no te sirve.",
    "Tu ser es un reflejo del amor que te brindas a ti misma.",
    "Cuando te enfocas en lo positivo, tu vida se llena de bendiciones.",
    "La serenidad es el regalo más hermoso que puedes darte a ti misma.",
    "La vida se vuelve más fácil cuando vives en el ahora.",
    "Tu alma tiene una belleza infinita, reconócelo todos los días.",
    "Cada día trae consigo nuevas oportunidades para crecer y evolucionar.",
    "Tu mente tiene el poder de sanar y crear la vida que deseas.",
    "La paz interna es el mejor regalo que puedes darle al mundo.",
    "Cada acción que tomas está alineada con tu propósito divino.",
    "La verdadera felicidad proviene de la conexión con tu ser interior.",
    "La energía positiva comienza con pensamientos positivos.",
    "La naturaleza tiene el poder de restaurar tu equilibrio.",
    "Cada pensamiento, palabra y acción tiene el poder de transformar tu vida.",
    "La espiritualidad es el camino hacia la paz interior.",
    "Cada paso que das hacia tu bienestar es un acto de valentía.",
    "Tu corazón sabe lo que es mejor para ti, solo debes escuchar.",
    "Cada desafío es una oportunidad para descubrir tu fortaleza interior.",
    "Recuerda que eres un ser infinito y lleno de posibilidades.",
    "La belleza de la vida está en los pequeños momentos de paz y alegría.",
    "La gratitud abre puertas a nuevas bendiciones en tu vida.",
    "Tu alma está en constante expansión, siempre hacia algo más grande.",
    "La meditación te conecta con tu verdad más profunda.",
    "La vida te da lo que necesitas, no lo que quieres.",
    "La conexión con tu ser interior es la clave para vivir con plenitud.",
    "Recuerda que todo lo que necesitas ya está dentro de ti.",
    "Cada respiración es un recordatorio de tu poder divino.",
    "Tu energía es una manifestación de tu vibración interna.",
    "Cuando te amas a ti misma, todo en tu vida comienza a fluir.",
    "La abundancia es el estado natural del universo, y es tuyo por derecho.",
    "El equilibrio en tu vida comienza con el equilibrio interno.",
    "La paz comienza con un pensamiento, luego con una acción.",
    "Tu luz brilla más fuerte cuando estás alineada con tu propósito.",
    "Cada día es una oportunidad para empezar de nuevo.",
    "La magia está en vivir el presente y en estar conectada contigo misma.",
    "Tú eres suficiente tal y como eres, no necesitas ser nada más.",
    "El equilibrio en tu vida es una práctica diaria.",
    "Cada desafío trae consigo una oportunidad de crecimiento.",
    "Tu alma ya sabe lo que es mejor para ti, confía en ella.",
    "El primer paso hacia la paz es la aceptación de ti misma.",
    "La sanación comienza cuando te permites sentir y liberar.",
    "Todo lo que necesitas para ser feliz está dentro de ti."
  ];
  
  export default frasesMotivadoras;